-- project-check: LLM-powered project standards checker
-- Generated by gotofish gen --release project-check
-- https://github.com/afeldman/project-check

food = {
    name = "project-check",
    description = "LLM-powered project standards checker",
    homepage = "https://github.com/afeldman/project-check",
    version = "0.0.0",
    packages = {
        {
            os = "darwin",
            arch = "amd64",
            url = "",
            sha256 = "",
            resources = {
                {
                    path = "project-check",
                    installpath = "bin/project-check",
                    executable = true
                }
            }
        }
    }
}
