-- scripts: Personal utility scripts for macOS and Linux
-- Generated by gotofish gen --bash
-- https://github.com/afeldman/scripts

food = {
    name = "scripts",
    description = "Personal utility scripts for macOS and Linux",
    homepage = "https://github.com/afeldman/scripts",
    version = "0.0.0",
    packages = {
        {
            os = "darwin",
            arch = "amd64",
            url = "",
            sha256 = "",
            resources = {
                { path = "scripts-0.0.0/gotofish", installpath = "bin/gotofish", executable = true },
            }
        }
    }
}
